services:
  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: mysql
    networks:
      - compose-bridge

  sicredi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
        TOKEN_CERTISIGN: '${TOKEN_CERTISIGN}'
        URL_CERTISIGN: '${URL_CERTISIGN}'
        HOST: '${HOST}'

    container_name: sicredi
    restart: always
    networks:
      - compose-bridge
    ports:
      - '${APP_PORT:-80}:80'
    depends_on:
          - mysql
    volumes:
        - .:/var/www/html
    environment:
      TOKEN_CERTISIGN: '${TOKEN_CERTISIGN}'
      URL_CERTISIGN: '${URL_CERTISIGN}'
      HOST: '${HOST}'


networks:
  compose-bridge:
    driver: bridge