version: "3.9"
services:
  mysql:
    image: mysql
    container_name: mysql
    networks:
      - compose-bridge

  sicredi:
    image: php:8.2-cli
    container_name: sicredi
    networks:
      - compose-bridge
    ports:
      - 3000:3000

networks:
  compose-bridge:
    driver: bridge